"use client";
import './globals.css';
import { Exo, Roboto, Alkatra } from 'next/font/google';

import 'bootstrap/dist/css/bootstrap.css';
import React, { useEffect } from 'react';
import Navbar from '../components/Navbar'

const exo = Exo({ subsets: ['latin'] })
const alkatara = Alkatra({ subsets: ['latin'] })

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {

  useEffect(() => {
    import("bootstrap/dist/js/bootstrap");
  }, []);

  return (

    <html lang='en'>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}